### ISSUE TITLE
Error: Call to a member function getProductPrice() on null in /lib/common/helpers/Inventory.php:443

### ISSUE THREAD

**Issue by codehog** [osCommerce/osCommerce-V4#38]
It appears that $priceInstance variable is not assigned correctly when the the following conditions are met.  The product has attributes and the b2b template is used to display the product.

To replicate:

Goto **ADMIN -> Products/Catalogue -> Attributes -> Products Attributes**
 - and create a new attribute group
 - double click and insert a new attribute value

Goto **ADMIN -> Products/Catalogue -> Products (Brands / Categories)**

 - Click "Add Product" button
 - Toggle the Status to active and SAVE
 - Click "Preview on site" button and choose b2bsupermarket    (This should display a minimal product page)

 - Go back to the product and click the "Attributes and Inventory Tab"
 - Double click at least one attribute to add it to the product
 - Click SAVE
 - Click "Preview on site" button and again choose b2bsupermarket (This now displays "please contact us if you see this page")
 
 ```
Stack trace:
#0 /home/dd/public_html/lib/frontend/controllers/CatalogController.php(1593): common\helpers\Inventory::getDetails(3, '3', Array)
#1 [internal function]: frontend\controllers\CatalogController->actionProductInventory()
#2 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /home/dd/public_html/lib/frontend/design/boxes/product/Inventory.php(36): yii\base\InlineAction->runWithParams(Array)
#4 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/Widget.php(146): frontend\design\boxes\product\Inventory->run()
#5 /home/dd/public_html/lib/frontend/design/Block.php(137): yii\base\Widget::widget(Array)
#6 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/Widget.php(146): frontend\design\Block->run()
#7 /home/dd/public_html/lib/frontend/design/boxes/BlockBox.php(110): yii\base\Widget::widget(Array)
#8 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/Widget.php(146): frontend\design\boxes\BlockBox->run()
#9 /home/dd/public_html/lib/frontend/design/Block.php(137): yii\base\Widget::widget(Array)
#10 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/Widget.php(146): frontend\design\Block->run()
#11 /home/dd/public_html/lib/frontend/design/boxes/BlockBox.php(110): yii\base\Widget::widget(Array)
#12 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/Widget.php(146): frontend\design\boxes\BlockBox->run()
#13 /home/dd/public_html/lib/frontend/design/Block.php(137): yii\base\Widget::widget(Array)
#14 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/Widget.php(146): frontend\design\Block->run()
#15 /home/dd/public_html/lib/frontend/design/boxes/BlockBox.php(110): yii\base\Widget::widget(Array)
#16 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/Widget.php(146): frontend\design\boxes\BlockBox->run()
#17 /home/dd/public_html/lib/frontend/design/Block.php(137): yii\base\Widget::widget(Array)
#18 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/Widget.php(146): frontend\design\Block->run()
#19 /home/dd/public_html/lib/frontend/runtime/Smarty/compile/a2f4682693d37ac5062e3708f076173dec3fea92_0.file.product.tpl.php(29): yii\base\Widget::widget(Array)
#20 /home/dd/public_html/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_644484e9eb2889_41308412(Object(Smarty_Internal_Template))
#21 /home/dd/public_html/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#22 /home/dd/public_html/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#23 /home/dd/public_html/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 0)
#24 /home/dd/public_html/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0)
#25 /home/dd/public_html/lib/vendor/yiisoft/yii2-smarty/src/ViewRenderer.php(268): Smarty_Internal_TemplateBase->fetch()
#26 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/View.php(261): yii\smarty\ViewRenderer->render(Object(common\components\View), '/home/dd/public...', Array)
#27 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/dd/public...', Array, Object(frontend\controllers\CatalogController))
#28 /home/dd/public_html/lib/frontend/controllers/Sceleton.php(972): yii\base\View->render('product.tpl', Array, Object(frontend\controllers\CatalogController))
#29 /home/dd/public_html/lib/frontend/controllers/CatalogController.php(492): frontend\controllers\Sceleton->render('product.tpl', Array)
#30 [internal function]: frontend\controllers\CatalogController->actionProduct()
#31 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#32 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#33 /home/dd/public_html/lib/frontend/controllers/Sceleton.php(232): yii\base\Controller->runAction('product', Array)
#34 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/Module.php(552): frontend\controllers\Sceleton->runAction('product', Array)
#35 /home/dd/public_html/lib/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('catalog/product', Array)
#36 /home/dd/public_html/lib/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(frontend\components\Request))
#37 /home/dd/public_html/lib/frontend/web/index.php(29): yii\base\Application->run()
#38 /home/dd/public_html/index.php(37): require('/home/dd/public...')
#39 {main}
```

**Comment by pan-oscom** [comment]
Thanks. The fix will be included in the next update.
